// Code generated by zapgen; DO NOT EDIT.
// source: reasoner_admin.zap

package admin

import (
	"fmt"
	"github.com/zap-proto/go/rpc"
)

// Method ordinals for the AdminReasoner service (stable 1-based wire ids).
const (
	AdminReasonerListReasonersOrdinal uint32 = 1
)

// AdminReasonerChannel ships one Call envelope and awaits its correlated Response.
type AdminReasonerChannel interface {
	Call(envelope []byte) (rpc.Response, error)
}

// AdminReasonerClient is a typed RPC client for the AdminReasoner service over a ZAP call channel.
// Each call takes a fresh PromiseID from sess; the pipelined "On" form of a
// method sets Target to a prior call's Promise so the server chains them.
type AdminReasonerClient struct {
	ch   AdminReasonerChannel
	cap  []byte
	sess *rpc.Session
}

// NewAdminReasonerClient returns a client that issues calls over ch, attaching cap
// (which may be nil) to every request.
func NewAdminReasonerClient(ch AdminReasonerChannel, capability []byte) *AdminReasonerClient {
	return &AdminReasonerClient{ch: ch, cap: capability, sess: rpc.NewSession()}
}

func (c *AdminReasonerClient) ListReasoners() (rpc.Promise, []byte, error) {
	return c.invokeListReasoners(rpc.NoTarget, nil)
}

// ListReasonersOn issues ListReasoners as a dependent call pipelined on the answer of on:
// the server substitutes on's resolved result for this call's payload
// before dispatch, so it ships without waiting for on to round-trip.
func (c *AdminReasonerClient) ListReasonersOn(on rpc.Promise) (rpc.Promise, []byte, error) {
	return c.invokeListReasoners(on.ID, nil)
}

func (c *AdminReasonerClient) invokeListReasoners(target uint32, payload []byte) (rpc.Promise, []byte, error) {
	p := c.sess.Next()
	resp, err := c.ch.Call(rpc.BuildRequest(rpc.Call{
		Method:    AdminReasonerListReasonersOrdinal,
		PromiseID: p.ID,
		Target:    target,
		Cap:       c.cap,
		Payload:   payload,
	}))
	if err != nil {
		return p, nil, err
	}
	if resp.Status != rpc.StatusOK {
		return p, nil, fmt.Errorf("AdminReasoner.ListReasoners: status %d", resp.Status)
	}
	return p, resp.Body, nil
}

// AdminReasonerHandler is the server contract for the AdminReasoner service. Implement each
// method, then route requests to it with DispatchAdminReasoner.
type AdminReasonerHandler interface {
	ListReasoners() ([]byte, error)
}

// DispatchAdminReasoner decodes a Call envelope, routes it by method ordinal to h,
// and returns the response envelope. An unknown ordinal yields a
// StatusNotFound response; a handler error yields StatusInternal.
func DispatchAdminReasoner(h AdminReasonerHandler, envelope []byte) ([]byte, error) {
	call, err := rpc.ParseRequest(envelope)
	if err != nil {
		return nil, err
	}
	switch call.Method {
	case AdminReasonerListReasonersOrdinal:
		body, err := h.ListReasoners()
		if err != nil {
			return rpc.BuildResponse(rpc.StatusInternal, call.PromiseID, nil), nil
		}
		return rpc.BuildResponse(rpc.StatusOK, call.PromiseID, body), nil
	default:
		return rpc.BuildResponse(rpc.StatusNotFound, call.PromiseID, nil), nil
	}
}
