// Code generated by zapgen; DO NOT EDIT.
// source: reasoner_admin.zap

package admin

import (
	zap "github.com/zap-proto/go"
)

const (
	listReasonersResponseReasonersOff = 0
	listReasonersResponseSize         = 8
)

// ListReasonersResponse is a zero-copy view into a ZAP-encoded ListReasonersResponse message.
type ListReasonersResponse struct{ o zap.Object }

// WrapListReasonersResponse parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapListReasonersResponse(b []byte) (ListReasonersResponse, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return ListReasonersResponse{}, err
	}
	return ListReasonersResponse{o: m.Root()}, nil
}

func (t ListReasonersResponse) Reasoners() zap.List {
	return t.o.List(listReasonersResponseReasonersOff)
}

// ListReasonersResponseInput collects the field values for NewListReasonersResponse.
type ListReasonersResponseInput struct {
	Reasoners [][]byte
}

// NewListReasonersResponse builds a ZAP-encoded ListReasonersResponse message from in and returns the bytes.
func NewListReasonersResponse(in ListReasonersResponseInput) []byte {
	b := zap.NewBuilder(256)
	ob := b.StartObject(listReasonersResponseSize)
	reasonersLB := b.StartList(0)
	for _, elem := range in.Reasoners {
		reasonersLB.AddObjectBytes(elem)
	}
	ob.SetList(listReasonersResponseReasonersOff, reasonersLB.FinishOffset(), len(in.Reasoners))
	ob.FinishAsRoot()
	return b.Finish()
}
