// Code generated by zapgen; DO NOT EDIT.
// source: reasoner_admin.zap

package admin

import (
	zap "github.com/zap-proto/go"
)

const (
	reasonerReasonerIdOff    = 0
	reasonerAgentNodeIdOff   = 8
	reasonerNameOff          = 16
	reasonerDescriptionOff   = 24
	reasonerStatusOff        = 32
	reasonerNodeVersionOff   = 40
	reasonerLastHeartbeatOff = 48
	reasonerSize             = 56
)

// Reasoner is a zero-copy view into a ZAP-encoded Reasoner message.
type Reasoner struct{ o zap.Object }

// WrapReasoner parses b and returns a typed view. Returns an error if the
// wire-level checks (magic, version, size) fail.
func WrapReasoner(b []byte) (Reasoner, error) {
	m, err := zap.Parse(b)
	if err != nil {
		return Reasoner{}, err
	}
	return Reasoner{o: m.Root()}, nil
}

func (t Reasoner) ReasonerId() string    { return t.o.Text(reasonerReasonerIdOff) }
func (t Reasoner) AgentNodeId() string   { return t.o.Text(reasonerAgentNodeIdOff) }
func (t Reasoner) Name() string          { return t.o.Text(reasonerNameOff) }
func (t Reasoner) Description() string   { return t.o.Text(reasonerDescriptionOff) }
func (t Reasoner) Status() string        { return t.o.Text(reasonerStatusOff) }
func (t Reasoner) NodeVersion() string   { return t.o.Text(reasonerNodeVersionOff) }
func (t Reasoner) LastHeartbeat() string { return t.o.Text(reasonerLastHeartbeatOff) }

// ReasonerInput collects the field values for NewReasoner.
type ReasonerInput struct {
	ReasonerId    string
	AgentNodeId   string
	Name          string
	Description   string
	Status        string
	NodeVersion   string
	LastHeartbeat string
}

// NewReasoner builds a ZAP-encoded Reasoner message from in and returns the bytes.
func NewReasoner(in ReasonerInput) []byte {
	b := zap.NewBuilder(256)
	ob := b.StartObject(reasonerSize)
	ob.SetText(reasonerReasonerIdOff, in.ReasonerId)
	ob.SetText(reasonerAgentNodeIdOff, in.AgentNodeId)
	ob.SetText(reasonerNameOff, in.Name)
	ob.SetText(reasonerDescriptionOff, in.Description)
	ob.SetText(reasonerStatusOff, in.Status)
	ob.SetText(reasonerNodeVersionOff, in.NodeVersion)
	ob.SetText(reasonerLastHeartbeatOff, in.LastHeartbeat)
	ob.FinishAsRoot()
	return b.Finish()
}
