// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: proto/admin/reasoner_admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListReasonersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReasonersRequest) Reset() {
	*x = ListReasonersRequest{}
	mi := &file_proto_admin_reasoner_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReasonersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReasonersRequest) ProtoMessage() {}

func (x *ListReasonersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_reasoner_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReasonersRequest.ProtoReflect.Descriptor instead.
func (*ListReasonersRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_reasoner_admin_proto_rawDescGZIP(), []int{0}
}

type Reasoner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReasonerId    string                 `protobuf:"bytes,1,opt,name=reasoner_id,json=reasonerId,proto3" json:"reasoner_id,omitempty"`
	AgentNodeId   string                 `protobuf:"bytes,2,opt,name=agent_node_id,json=agentNodeId,proto3" json:"agent_node_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	NodeVersion   string                 `protobuf:"bytes,6,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	LastHeartbeat string                 `protobuf:"bytes,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reasoner) Reset() {
	*x = Reasoner{}
	mi := &file_proto_admin_reasoner_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reasoner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reasoner) ProtoMessage() {}

func (x *Reasoner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_reasoner_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reasoner.ProtoReflect.Descriptor instead.
func (*Reasoner) Descriptor() ([]byte, []int) {
	return file_proto_admin_reasoner_admin_proto_rawDescGZIP(), []int{1}
}

func (x *Reasoner) GetReasonerId() string {
	if x != nil {
		return x.ReasonerId
	}
	return ""
}

func (x *Reasoner) GetAgentNodeId() string {
	if x != nil {
		return x.AgentNodeId
	}
	return ""
}

func (x *Reasoner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Reasoner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Reasoner) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Reasoner) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *Reasoner) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

type ListReasonersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reasoners     []*Reasoner            `protobuf:"bytes,1,rep,name=reasoners,proto3" json:"reasoners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReasonersResponse) Reset() {
	*x = ListReasonersResponse{}
	mi := &file_proto_admin_reasoner_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReasonersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReasonersResponse) ProtoMessage() {}

func (x *ListReasonersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_reasoner_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReasonersResponse.ProtoReflect.Descriptor instead.
func (*ListReasonersResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_reasoner_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListReasonersResponse) GetReasoners() []*Reasoner {
	if x != nil {
		return x.Reasoners
	}
	return nil
}

var File_proto_admin_reasoner_admin_proto protoreflect.FileDescriptor

const file_proto_admin_reasoner_admin_proto_rawDesc = "" +
	"\n" +
	" proto/admin/reasoner_admin.proto\x12\badmin.v1\"\x16\n" +
	"\x14ListReasonersRequest\"\xe7\x01\n" +
	"\bReasoner\x12\x1f\n" +
	"\vreasoner_id\x18\x01 \x01(\tR\n" +
	"reasonerId\x12\"\n" +
	"\ragent_node_id\x18\x02 \x01(\tR\vagentNodeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fnode_version\x18\x06 \x01(\tR\vnodeVersion\x12%\n" +
	"\x0elast_heartbeat\x18\a \x01(\tR\rlastHeartbeat\"I\n" +
	"\x15ListReasonersResponse\x120\n" +
	"\treasoners\x18\x01 \x03(\v2\x12.admin.v1.ReasonerR\treasoners2h\n" +
	"\x14AdminReasonerService\x12P\n" +
	"\rListReasoners\x12\x1e.admin.v1.ListReasonersRequest\x1a\x1f.admin.v1.ListReasonersResponseB\x1bZ\x19hanzo_agents/pkg/adminpb;adminpbb\x06proto3"

var (
	file_proto_admin_reasoner_admin_proto_rawDescOnce sync.Once
	file_proto_admin_reasoner_admin_proto_rawDescData []byte
)

func file_proto_admin_reasoner_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_reasoner_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_reasoner_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_reasoner_admin_proto_rawDesc), len(file_proto_admin_reasoner_admin_proto_rawDesc)))
	})
	return file_proto_admin_reasoner_admin_proto_rawDescData
}

var file_proto_admin_reasoner_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_admin_reasoner_admin_proto_goTypes = []any{
	(*ListReasonersRequest)(nil),  // 0: admin.v1.ListReasonersRequest
	(*Reasoner)(nil),              // 1: admin.v1.Reasoner
	(*ListReasonersResponse)(nil), // 2: admin.v1.ListReasonersResponse
}
var file_proto_admin_reasoner_admin_proto_depIdxs = []int32{
	1, // 0: admin.v1.ListReasonersResponse.reasoners:type_name -> admin.v1.Reasoner
	0, // 1: admin.v1.AdminReasonerService.ListReasoners:input_type -> admin.v1.ListReasonersRequest
	2, // 2: admin.v1.AdminReasonerService.ListReasoners:output_type -> admin.v1.ListReasonersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_admin_reasoner_admin_proto_init() }
func file_proto_admin_reasoner_admin_proto_init() {
	if File_proto_admin_reasoner_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_reasoner_admin_proto_rawDesc), len(file_proto_admin_reasoner_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_reasoner_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_reasoner_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_reasoner_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_reasoner_admin_proto = out.File
	file_proto_admin_reasoner_admin_proto_goTypes = nil
	file_proto_admin_reasoner_admin_proto_depIdxs = nil
}
