// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.33.4
// source: control-plane/proto/admin/reasoner_admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListReasonersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListReasonersRequest) Reset() {
	*x = ListReasonersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_plane_proto_admin_reasoner_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReasonersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReasonersRequest) ProtoMessage() {}

func (x *ListReasonersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_admin_reasoner_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReasonersRequest.ProtoReflect.Descriptor instead.
func (*ListReasonersRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_admin_reasoner_admin_proto_rawDescGZIP(), []int{0}
}

type Reasoner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReasonerId    string `protobuf:"bytes,1,opt,name=reasoner_id,json=reasonerId,proto3" json:"reasoner_id,omitempty"`
	AgentNodeId   string `protobuf:"bytes,2,opt,name=agent_node_id,json=agentNodeId,proto3" json:"agent_node_id,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	NodeVersion   string `protobuf:"bytes,6,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	LastHeartbeat string `protobuf:"bytes,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
}

func (x *Reasoner) Reset() {
	*x = Reasoner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_plane_proto_admin_reasoner_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reasoner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reasoner) ProtoMessage() {}

func (x *Reasoner) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_admin_reasoner_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reasoner.ProtoReflect.Descriptor instead.
func (*Reasoner) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_admin_reasoner_admin_proto_rawDescGZIP(), []int{1}
}

func (x *Reasoner) GetReasonerId() string {
	if x != nil {
		return x.ReasonerId
	}
	return ""
}

func (x *Reasoner) GetAgentNodeId() string {
	if x != nil {
		return x.AgentNodeId
	}
	return ""
}

func (x *Reasoner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Reasoner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Reasoner) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Reasoner) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *Reasoner) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

type ListReasonersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reasoners []*Reasoner `protobuf:"bytes,1,rep,name=reasoners,proto3" json:"reasoners,omitempty"`
}

func (x *ListReasonersResponse) Reset() {
	*x = ListReasonersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_plane_proto_admin_reasoner_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReasonersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReasonersResponse) ProtoMessage() {}

func (x *ListReasonersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_admin_reasoner_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReasonersResponse.ProtoReflect.Descriptor instead.
func (*ListReasonersResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_admin_reasoner_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListReasonersResponse) GetReasoners() []*Reasoner {
	if x != nil {
		return x.Reasoners
	}
	return nil
}

var File_control_plane_proto_admin_reasoner_admin_proto protoreflect.FileDescriptor

var file_control_plane_proto_admin_reasoner_admin_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2d, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xe7, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c,
	0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x22, 0x49, 0x0a, 0x15,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x73, 0x32, 0x68, 0x0a, 0x14, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x50, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x73,
	0x12, 0x1e, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x68, 0x61, 0x6e, 0x7a, 0x6f, 0x61, 0x69, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2d, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_control_plane_proto_admin_reasoner_admin_proto_rawDescOnce sync.Once
	file_control_plane_proto_admin_reasoner_admin_proto_rawDescData = file_control_plane_proto_admin_reasoner_admin_proto_rawDesc
)

func file_control_plane_proto_admin_reasoner_admin_proto_rawDescGZIP() []byte {
	file_control_plane_proto_admin_reasoner_admin_proto_rawDescOnce.Do(func() {
		file_control_plane_proto_admin_reasoner_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_control_plane_proto_admin_reasoner_admin_proto_rawDescData)
	})
	return file_control_plane_proto_admin_reasoner_admin_proto_rawDescData
}

var file_control_plane_proto_admin_reasoner_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_control_plane_proto_admin_reasoner_admin_proto_goTypes = []interface{}{
	(*ListReasonersRequest)(nil),  // 0: admin.v1.ListReasonersRequest
	(*Reasoner)(nil),              // 1: admin.v1.Reasoner
	(*ListReasonersResponse)(nil), // 2: admin.v1.ListReasonersResponse
}
var file_control_plane_proto_admin_reasoner_admin_proto_depIdxs = []int32{
	1, // 0: admin.v1.ListReasonersResponse.reasoners:type_name -> admin.v1.Reasoner
	0, // 1: admin.v1.AdminReasonerService.ListReasoners:input_type -> admin.v1.ListReasonersRequest
	2, // 2: admin.v1.AdminReasonerService.ListReasoners:output_type -> admin.v1.ListReasonersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_control_plane_proto_admin_reasoner_admin_proto_init() }
func file_control_plane_proto_admin_reasoner_admin_proto_init() {
	if File_control_plane_proto_admin_reasoner_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_control_plane_proto_admin_reasoner_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReasonersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_plane_proto_admin_reasoner_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reasoner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_plane_proto_admin_reasoner_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReasonersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_control_plane_proto_admin_reasoner_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_plane_proto_admin_reasoner_admin_proto_goTypes,
		DependencyIndexes: file_control_plane_proto_admin_reasoner_admin_proto_depIdxs,
		MessageInfos:      file_control_plane_proto_admin_reasoner_admin_proto_msgTypes,
	}.Build()
	File_control_plane_proto_admin_reasoner_admin_proto = out.File
	file_control_plane_proto_admin_reasoner_admin_proto_rawDesc = nil
	file_control_plane_proto_admin_reasoner_admin_proto_goTypes = nil
	file_control_plane_proto_admin_reasoner_admin_proto_depIdxs = nil
}
